

services:
  flask-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "5000:5000"
    networks:
      - traffic-net

  data-sender:
    build:
      context: .
      dockerfile: Dockerfile.sender
    depends_on:
      - flask-server
    network_mode: host
    # Альтернатива, если network_mode: host не работает на вашей ОС:
    # environment:
    #   - SERVER_URL=http://flask-server:5000/package
    # command: sh -c "sleep 5 && python data_generation.py"

networks:
  traffic-net:
    driver: bridge